apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pulsar-system

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - server-deployment.yaml
  - server-service.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - worker-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
