apiVersion: v1
kind: Service
metadata:
  name: pulsar-server-service
  namespace: pulsar-system
  labels:
    app: pulsar-server
spec:
  selector:
    app: pulsar-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
