apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultflow

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: vaultflow
  app.kubernetes.io/managed-by: kustomize

images:
  - name: vaultflow/api
    newTag: "1.0.0"
  - name: vaultflow/ui
    newTag: "1.0.0"
