/**
 * NexusFinance Prometheus Metrics
 *
 * Prometheus is a monitoring system that scrapes metrics from your app.
 * Grafana then visualizes those metrics as dashboards.
 *
 * What we measure:
 *   1. HTTP request count and duration (is the API slow?)
 *   2. Number of transactions processed per second
 *   3. Active user session count
 *   4. Fraud alerts fired
 *   5. Loan approval rate
 *   6. Node.js internals (CPU, memory, garbage collection)
 *
 * Prometheus scrapes GET /metrics every 15 seconds.
 * Grafana reads from Prometheus and shows beautiful graphs.
 */

import { RequestHandler } from 'express';
import client from 'prom-client';

// Enable default Node.js metrics (CPU, memory, event loop lag, GC)
client.collectDefaultMetrics({ prefix: 'nexusfinance_node_' });

// ── Custom Business Metrics ─────────────────────────────────────────────────

// How long do HTTP requests take? (histogram = distribution of values)
export const httpDuration = new client.Histogram({
  name:    'nexusfinance_http_request_duration_seconds',
  help:    'HTTP request duration in seconds',
  labelNames: ['method', 'route', 'status'],
  // Buckets: time thresholds we measure against (in seconds)
  // This lets Prometheus calculate: "90% of requests complete in < 100ms"
  buckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5],
});

// How many transactions have been processed?
export const transactionsTotal = new client.Counter({
  name:       'nexusfinance_transactions_total',
  help:       'Total financial transactions processed',
  labelNames: ['type', 'currency', 'status'],
  // type: transfer | deposit | withdrawal | payment
  // status: completed | failed | pending
});

// How many users are active right now?
export const activeSessions = new client.Gauge({
  name: 'nexusfinance_active_sessions',
  help: 'Number of active user sessions',
});

// How many fraud alerts have been triggered?
export const fraudAlertsTotal = new client.Counter({
  name:       'nexusfinance_fraud_alerts_total',
  help:       'Fraud alerts generated by the fraud detection system',
  labelNames: ['severity', 'type'],
  // severity: low | medium | high | critical
  // type: velocity | geo_anomaly | amount_spike | pattern
});

// What percentage of loan applications are approved?
export const loanApprovalRate = new client.Gauge({
  name: 'nexusfinance_loan_approval_rate_percent',
  help: 'Current loan application approval rate (0-100%)',
});

// How much money is being processed?
export const paymentVolumeUsd = new client.Counter({
  name:    'nexusfinance_payment_volume_usd_total',
  help:    'Total payment volume processed in USD',
  labelNames: ['type'],
});

// ── Middleware ──────────────────────────────────────────────────────────────

export function metricsMiddleware(): RequestHandler {
  return (req, res, next) => {
    const startTime = Date.now();

    res.on('finish', () => {
      // Use route path pattern (not actual URL) to avoid high cardinality
      // Bad:  /api/v1/accounts/abc-123-def  (millions of unique labels)
      // Good: /api/v1/accounts/:id           (one label per route)
      const route = (req.route?.path ?? req.path).replace(/\/[0-9a-f-]{36}/g, '/:id');

      httpDuration
        .labels(req.method, route, String(res.statusCode))
        .observe((Date.now() - startTime) / 1000);
    });

    next();
  };
}

// The /metrics endpoint that Prometheus scrapes
export function metricsRoute(): RequestHandler {
  return async (_req, res) => {
    res.set('Content-Type', client.register.contentType);
    res.end(await client.register.metrics());
  };
}
