apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medicore

resources:
  - ../../base

commonLabels:
  environment: production

images:
  - name: medicore/auth-service
    newTag: latest
  - name: medicore/patient-service
    newTag: latest
  - name: medicore/appointment-service
    newTag: latest
  - name: medicore/analytics-service
    newTag: latest
  - name: medicore/frontend
    newTag: latest
