apiVersion: v1
kind: Service
metadata:
  name: shieldgrid-api
  namespace: shieldgrid
  labels:
    app: shieldgrid-api
spec:
  selector:
    app: shieldgrid-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shieldgrid-api
  namespace: shieldgrid
  annotations:
    eks.amazonaws.com/role-arn: SHIELDGRID_API_IAM_ROLE_ARN
