apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shieldgrid

resources:
  - namespace.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - ingress.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: shieldgrid
