// Package metrics registers and exposes Prometheus metrics for VaultFlow.
package metrics

import (
	"net/http"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

const defaultNamespace = "vaultflow"

// Registry holds all VaultFlow Prometheus collectors.
type Registry struct {
	namespace string

	// API
	HTTPRequestsTotal    *prometheus.CounterVec
	HTTPRequestDuration  *prometheus.HistogramVec
	HTTPActiveRequests   prometheus.Gauge

	// Financial
	TransactionsProcessed  *prometheus.CounterVec
	TransactionAmount      *prometheus.HistogramVec
	ReconciliationRuns     *prometheus.CounterVec
	ReconciliationDuration prometheus.Histogram
	AlertsGenerated        *prometheus.CounterVec
	BudgetUtilization      *prometheus.GaugeVec
	ForecastAccuracy       prometheus.Histogram

	// Cache
	CacheHits   *prometheus.CounterVec
	CacheMisses *prometheus.CounterVec

	// Provider
	ProviderSyncDuration *prometheus.HistogramVec
	ProviderSyncErrors   *prometheus.CounterVec
}

// New creates and registers all VaultFlow metrics with the given namespace.
func New(namespace string) *Registry {
	if namespace == "" {
		namespace = defaultNamespace
	}

	r := &Registry{namespace: namespace}

	r.HTTPRequestsTotal = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "http",
		Name:      "requests_total",
		Help:      "Total number of HTTP requests by method, path, and status.",
	}, []string{"method", "path", "status"})

	r.HTTPRequestDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: "http",
		Name:      "request_duration_seconds",
		Help:      "HTTP request latency distribution.",
		Buckets:   prometheus.DefBuckets,
	}, []string{"method", "path"})

	r.HTTPActiveRequests = promauto.NewGauge(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "http",
		Name:      "active_requests",
		Help:      "Number of HTTP requests currently being served.",
	})

	r.TransactionsProcessed = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "finance",
		Name:      "transactions_processed_total",
		Help:      "Total transactions processed by type and status.",
	}, []string{"type", "status", "currency"})

	r.TransactionAmount = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: "finance",
		Name:      "transaction_amount",
		Help:      "Distribution of transaction amounts.",
		Buckets:   []float64{1, 10, 50, 100, 500, 1000, 5000, 10000, 50000},
	}, []string{"type", "currency"})

	r.ReconciliationRuns = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "reconciliation",
		Name:      "runs_total",
		Help:      "Total reconciliation runs by outcome.",
	}, []string{"status"})

	r.ReconciliationDuration = promauto.NewHistogram(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: "reconciliation",
		Name:      "duration_seconds",
		Help:      "Reconciliation run duration.",
		Buckets:   []float64{0.1, 0.5, 1, 5, 10, 30, 60},
	})

	r.AlertsGenerated = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "alerting",
		Name:      "generated_total",
		Help:      "Total alerts generated by severity.",
	}, []string{"severity", "source"})

	r.BudgetUtilization = promauto.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "budget",
		Name:      "utilization_percent",
		Help:      "Current budget utilization percentage.",
	}, []string{"tenant_id", "category"})

	r.ForecastAccuracy = promauto.NewHistogram(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: "forecast",
		Name:      "accuracy_percent",
		Help:      "Forecast accuracy measured against actuals.",
		Buckets:   []float64{50, 60, 70, 75, 80, 85, 90, 95, 98, 100},
	})

	r.CacheHits = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "cache",
		Name:      "hits_total",
		Help:      "Cache hits by key type.",
	}, []string{"key_type"})

	r.CacheMisses = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "cache",
		Name:      "misses_total",
		Help:      "Cache misses by key type.",
	}, []string{"key_type"})

	r.ProviderSyncDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: "provider",
		Name:      "sync_duration_seconds",
		Help:      "Duration of external provider sync operations.",
		Buckets:   []float64{1, 5, 10, 30, 60, 120, 300},
	}, []string{"provider"})

	r.ProviderSyncErrors = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "provider",
		Name:      "sync_errors_total",
		Help:      "Total provider sync errors by provider and error type.",
	}, []string{"provider", "error_type"})

	return r
}

// Handler returns the Prometheus HTTP handler.
func Handler() http.Handler { return promhttp.Handler() }
