// Re-export Lucide React icons under the names used across the codebase.
// Lucide gives pixel-perfect, professionally designed SVG icons.
export {
  LayoutDashboard  as IconGrid,
  ArrowLeftRight   as IconArrows,
  PieChart         as IconPieChart,
  Target           as IconTarget,
  TrendingUp       as IconTrendUp,
  Briefcase        as IconBriefcase,
  RefreshCcw       as IconRefresh,
  Bell             as IconBell,
  Activity         as IconActivity,
  ShieldCheck      as IconShield,
  Check            as IconCheck,
  Wifi             as IconWifi,
  Server           as IconServer,
  Zap              as IconZap,
  AlertTriangle    as IconAlertTriangle,
  Info             as IconInfo,
  XCircle          as IconXCircle,
  DollarSign       as IconDollar,
  Search           as IconSearch,
  Calendar         as IconCalendar,
  Cpu              as IconCpu,
  Layers           as IconLayers,
  LogOut           as IconLogOut,
  ChevronRight     as IconChevronRight,
  CircleDot        as IconCircleDot,
  BarChart3        as IconBarChart,
  Wallet           as IconWallet,
  Receipt          as IconReceipt,
  LineChart        as IconLineChart,
  ScanLine         as IconScan,
} from 'lucide-react';
