apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medicore-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

images:
  - name: medicore/auth-service
    newTag: latest
  - name: medicore/patient-service
    newTag: latest
  - name: medicore/appointment-service
    newTag: latest
  - name: medicore/analytics-service
    newTag: latest
  - name: medicore/frontend
    newTag: latest

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 5
    target:
      kind: HorizontalPodAutoscaler
