apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medicart-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: medicart-platform
    company.medicart/team: platform-engineering
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: medicart

  source:
    repoURL: https://github.com/medicart-health/medicart-platform
    targetRevision: HEAD
    path: helm/medicart
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
      parameters:
        - name: image.tag
          value: latest

  destination:
    server: https://kubernetes.default.svc
    namespace: medicart

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
