apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vendorvault

resources:
  - ../../base

# ArgoCD/CI updates these tags automatically on each deploy
images:
  - name: vendorvault-backend
    newTag: "latest"
  - name: vendorvault-frontend
    newTag: "latest"

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: vendorvault-backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: vendorvault-frontend
